### ISSUE TITLE
Woocommerce product links not automatically created

### ISSUE THREAD

**Issue by jdrda** [yasglobal/permalinks-customizer#10]
(copy from WP plugin support page)
 If I “regenerate permalink” on product page, everyting is OK. But if I import product via WP All Import, product permalink is not created. The category, brand and all things from taxonomies are created successfully.  

PostTypes settings: (also tried %postname%) 
post: %title% 
product: %title%  

Taxonomies settings: 
category: %slug% 
pwb-brand: %slug% 
product_cat: %slug% 
product_tag: %slug% 

Wordpress: 4.9.2 cs_cz
Woocommerce: 3.2.6
WP All Import Pro: 4.3.0
WP All Import  - Woocommerce Addon Pro: 2.2.9
Template: Storefrom 2.2.6

**Comment by samiahmedsiddiqui** [comment]
@jdrda Thanks for your feedback i'll check this issue and would contact you back.

Regards,
Sami

**Comment by samiahmedsiddiqui** [comment]
@jdrda WP All Import is the Purchased plugin so i can't check the issue with it or fixed it.

**Comment by samiahmedsiddiqui** [comment]
@jdrda Can you provide me the Plugin for the testing purpose?

**Comment by samiahmedsiddiqui** [comment]
@jdrda Patch added in the v2.2.0 Once you get sometime so please test it out.
