### ISSUE TITLE
Changes to PostTypes Settings Not Saving

### ISSUE THREAD

**Issue by hutzie** [yasglobal/permalinks-customizer#16]
When trying to define the permalink for our "Knowledge Base" post type, my changes will not save. Currently, the permalink is /knowledgebase/ but we'd like it to be /knowledgebase/%postname%. When I make the change and hit "Save Changes" it reverts back to /knowledgebase/. The same behavior persists when I try to change it to /knowlegebase/%title%.

Any help would be appreciated.

**Comment by samiahmedsiddiqui** [comment]
Hi @hutzie 

Are you getting any sort of error while saving settings? Does the issue only occurs for the "Knowledge base" post type or does it have with all the post types?

Can you provide screenshot of the settings page?

Thanks,
Sami

**Comment by hutzie** [comment]
![2018-08-15 11_47_15-posttypes settings ams controls wordpress](https://user-images.githubusercontent.com/25539426/44160738-05015980-a081-11e8-9744-311e2dd1de02.png)

I'm not getting any error, it just reverts to /knowledgebase/ when I return to the screen.

I use %postname% on Posts and it doesn't seem to have a problem. I added %postname% to the Popups type and it worked fine. So the problem seems to be solely with the knowledgebase post type.

**Comment by samiahmedsiddiqui** [comment]
@hutzie Try to make the field empty. Also, are you getting settings saved message or not?

**Comment by hutzie** [comment]
I was able to make the field empty and got a message confirming the save.

**Comment by hutzie** [comment]
After the clear, it was able to retain the changes. 
![2018-08-15 11_55_01-posttypes settings ams controls wordpress](https://user-images.githubusercontent.com/25539426/44161147-1c8d1200-a082-11e8-958f-ae53e56c243f.png)

**Comment by hutzie** [comment]
I went to regenerate permalinks, but they failed. 

![2018-08-15 11_56_35-knowledge base ams controls wordpress](https://user-images.githubusercontent.com/25539426/44161242-59590900-a082-11e8-8b66-b06da98c88e8.png)

And the changes are now gone.

![2018-08-15 11_57_20-posttypes settings ams controls wordpress](https://user-images.githubusercontent.com/25539426/44161261-6a097f00-a082-11e8-85f1-c9bf832a6352.png)

**Comment by samiahmedsiddiqui** [comment]
@hutzie Great 😄 I have tried to save the settings on my end and it looks fine to me. No issues occurred.

**Comment by samiahmedsiddiqui** [comment]
@hutzie As concerned about your Regenerate Permalinks issues so it's not failed. It gives you the message "0 Permalinks have been regenerated." That means the newly generated permainks are the same as the previous one. That's why this message is popping up.

Secondly, looks a like that there is some issue with your Knowledge base Post Types as others are working fine. How you have created this Post Type? Using CPT UI Plugin or from theme? I suggest you to recheck the settings of your Knowledge Base Post Type.

**Comment by hutzie** [comment]
I inherited this system, but it looks like they created this post type in a theme. Apparently, the /knowledgebase/%postname% worked up until a month or two ago, and they regenerated permalinks to /knowledgebase/ to get links working again. Now they'd like them back to post names, but I don't see any way to do that using your plugin considering the problem we're seeing.

I'm not a developer, so I can't really dig into the themes very deeply. Would uninstalling this plugin break the existing permalinks?

**Comment by samiahmedsiddiqui** [comment]
> I'm not a developer, so I can't really dig into the themes very deeply. Would uninstalling this plugin break the existing permalinks?

Yes, it will break other Permalinks.

For working on the knowledgebase, i suggest you to exclude the knowledgebase PostType from the plugin. You can do that as mentioned here:
https://github.com/yasglobal/permalinks-customizer#exclude-posttype-from-the-plugin

Let me know, if you have any other question.

Thanks,
Sami

**Comment by samiahmedsiddiqui** [comment]
As per not getting any response from past 2 months, i am closing this issue. Feel free to open it again if needed.

Thanks,
Sami

**Comment by hutzie** [comment]
It’s actually resolved – at some point it allowed me to save the changes and regenerate permalinks again. I wish I knew how or why, but I’m just happy it worked. Thanks so much!

Heather Allman
Director of Support & Communications

AMS Controls Inc.
T: +1 314.344.3144 ext: 118
F: +1 314.344.9996
hallman@amscontrols.com<mailto:hallman@amscontrols.com>
www.amscontrols.com<http://www.amscontrols.com/>

**Comment by samiahmedsiddiqui** [comment]
@hutzie Glad to hear that 😄
