### ISSUE TITLE
Issue With Latest Update

### ISSUE THREAD

**Issue by diydoctor** [yasglobal/permalinks-customizer#18]
Hi

I have just updated to your latest plugin version on our dev site but on testing the “permalink_customizer” field that is normally listed under Custom Fields in the post edit view is no longer visible?

This may be linked to the latest ACF plugin update (more info: https://wordpress.stackexchange.com/questions/277388/how-to-fix-missing-custom-fields-after-upgrading-to-wordpress-4-8-1) that for some reason has decided to hide the stock WP custom field list in post edit view

Although as far as I can see the correct custom permalink are being used for a given page where I have added them, it would be good if you could add back the permalink_customizer field under the custom fields list

Is this possible?

Kind Regards

**Comment by samiahmedsiddiqui** [comment]
@diydoctor This field in removed from the Custom Fields in the latest version due to not having any need of that there and also creating some issues when the users doesn't know what it is really about and they got confused with it.

**Comment by diydoctor** [comment]
Cool, no worries at all, thanks for confirming this, much appreciated

**Comment by diydoctor** [comment]
Hi

Just dropping a quick message – I’m having some issues with your permalink customizer plugin in that for an already published and live page, I am unable to change the permalink in the page edit screen.

If I make changes to the permalink and then hit publish, nothing is saved? Additionally, If I then regenerate the permalink and try to make changes, again no changes are saved when hit press publish.

I am using your latest version of the plugin and also other plugins that include:

Yoast seo
Wp super cache
Advanced custom fields
Autoptimise
Classic editor
Genesis theme and genesis simple sidebars
Wp rocket lazy load
Search wp
Max mega menu

I have cleared all caches and even cleared and restarted php fpm and memcache and the issue still persists

The permalink I am trying to change is for the following page: https://www.diydoctor.org.uk/blog/2019/06/how-to-paint-over-varnish-learn-how-to-correctly-prepare-varnished-surfaces-for-painting-and-paint-them-to-get-a-great-lasting-finish/

The permalink for this page was https://www.diydoctor.org.uk/projects/paint-varnish.htm  but after regenerating the permalink it has changed to the above which now results in a 404 and the page is now inaccessible

Can you help at all as I need to get this issue resolved

Kind Regards





James Gardner
Web Development
www.diydoctor.org.uk<http://www.diydoctor.org.uk/>
DIY Doctor Ltd Foundations Up, The Workshop, Newbury Works, Coleford, Somerset, BA3 5RX
Tel: 08456 342179 - calls cost 2p per minute plus your phone service providers access charge
Watch our new YouTube videos on 'How to avoid Cowboy Builders' - Click through to our channel<http://www.youtube.com/user/TheDIYDoctor>
You can now follow DIY Doctor on Facebook<http://www.facebook.com/pages/DIY-Doctor/114549991938058> and Twitter<http://twitter.com/DIYDoctor>

**Comment by samiahmedsiddiqui** [comment]
@diydoctor Please create a new issue for this. Secondly, I need access to your site to check this issue.

**Comment by diydoctor** [comment]
Hi Sami

Thanks for coming back to me

Apologies, I think I have now resolved the issue – I have just cleared all caches again and done another full php restart and the issue now seems to be fixed

Many thanks for your help

Kind Regards





James Gardner
Web Development
www.diydoctor.org.uk<http://www.diydoctor.org.uk/>
DIY Doctor Ltd Foundations Up, The Workshop, Newbury Works, Coleford, Somerset, BA3 5RX
Tel: 08456 342179 - calls cost 2p per minute plus your phone service providers access charge
Watch our new YouTube videos on 'How to avoid Cowboy Builders' - Click through to our channel<http://www.youtube.com/user/TheDIYDoctor>
You can now follow DIY Doctor on Facebook<http://www.facebook.com/pages/DIY-Doctor/114549991938058> and Twitter<http://twitter.com/DIYDoctor>

**Comment by samiahmedsiddiqui** [comment]
Good to know that 😄
