### ISSUE TITLE
How to show child-tax? 

### ISSUE THREAD

**Issue by mastaru** [yasglobal/permalinks-customizer#19]
I have custom post type. 
I want to create permalinks like this http://mysite.com/<%ctax_custom_taxonomy%>/%child-tax%/%postname%.

**Comment by mastaru** [comment]
I used <%ctax_services-category%>/%all_parents_postname% but it's don't show child taxonomy

**Comment by samiahmedsiddiqui** [comment]
Hi @mastaru 

<%ctax_custom_taxonomy%> only add parent Taxonomy in the Permalink. There is no tag available by which you can add the Parent and Child Taxonomies in the permalink.

Marking this as the enhancement of the available tags and will be available in the upcoming release.

Thanks,
Sami

**Comment by mastaru** [comment]
You realised v. 2.5.0. Did you fix this problem in this version?

**Comment by samiahmedsiddiqui** [comment]
@mastaru Oops i forgot this request, will be added separately.

Let's add it in v2.5.1, which may release in a day or two.

**Comment by samiahmedsiddiqui** [comment]
> I used <%ctax_services-category%>/%all_parents_postname% but it's don't show child taxonomy

@mastaru Looks Like that you have created the child taxonomy first and then create parent taxonomy. I have checked today and `<%ctax_custom_taxonomy%>` tag includes child taxonomies as well if term id of child taxonomy is less than to parent taxonomy or vice versa

In other words, it works only when you first create parent taxonomy and then create child taxonomy otherwise it only includes the parent taxonomy.

**Comment by mastaru** [comment]
[0] => WP_Term Object
        (
            [term_id] => 64
            [name] => Dyson
            [slug] => servisnii-centr-dyson
            [term_group] => 0
            [term_taxonomy_id] => 64
            [taxonomy] => services-category
            [description] => 
            [parent] => 0
            [count] => 87
            [filter] => raw
        )

    [1] => WP_Term Object
        (
            [term_id] => 69
            [name] => Освещение
            [slug] => osveshhenie-bosh-dayson
            [term_group] => 0
            [term_taxonomy_id] => 69
            [taxonomy] => services-category
            [description] => 
            [parent] => 64
            [count] => 1
            [filter] => raw
        )

My URL look like this -> sitename.com/servisnii-centr-dyson/jake-dyson-csys,
I want that my URL look like this -> sitename.com/servisnii-centr-dyson/osveshhenie-bosh-dayson/jake-dyson-csys,
Post type setting: <%ctax_services-category%>/%all_parents_postname%

**Comment by samiahmedsiddiqui** [comment]
@mastaru Apology. Actually the tag check for the lowest term id and use that in permalink, which is normally the parent term id. That's why you are getting this issue.

I am thinking to use the `Primary Category` in Permalink which is provided by yoast seo. Do you think it works in your case?

**Comment by mastaru** [comment]
Ok, let's try it. I use yoast seo. I will be very happy if it work :). Thank you for fast answers :+1:

**Comment by samiahmedsiddiqui** [comment]
https://github.com/yasglobal/permalinks-customizer/commit/2a47f4379a27841d8d7ee7c9ef88eefd69eac040

**Comment by samiahmedsiddiqui** [comment]
@mastaru I have applied the changes, now the `<%ctax_services-category%>` use the category selected as primary category in Yoast SEO.

Please update to the latest version and provide your feedback.

**Comment by mastaru** [comment]
Ok, I update plugin, and regenerate url, but it still  have same view... Maybe I do something wrong?

**Comment by samiahmedsiddiqui** [comment]
@mastaru What's the Primary Category selected in your Post?

**Comment by mastaru** [comment]
Dyson(id 64)

**Comment by samiahmedsiddiqui** [comment]
@mastaru That's why you are not getting change in Permalink. You need to select the Child Category from there.

**Comment by mastaru** [comment]
Yes, it works! Thank you very much! Best regards!

**Comment by samiahmedsiddiqui** [comment]
Great to hear that!
