### ISSUE TITLE
<%ctaxparents_custom_taxonomy%> show only fist parent tax

### ISSUE THREAD

**Issue by mastaru** [yasglobal/permalinks-customizer#21]
I use <%ctaxparents_custom_taxonomy%> for my custom post type, but link have only first parent tax.

It look like this: 

site.com/parent_tax/post

I want it look like this

site.com/parent_tax/child_1/child_2/post

 ID parent tax less than child tax. 
Fir example:
Parent id tax - 22
1 child  - 37
2 child - 40

![screenshot_2](https://user-images.githubusercontent.com/35373177/51262716-f7e7ee00-19c3-11e9-8494-8a552e1dc711.png)

**Comment by samiahmedsiddiqui** [comment]
Hi @mastaru 

Sorry for delay in my response i was on vacations and does not get time to reply to the queries.

As per your issue, May i ask that either you have selected multiple taxonomies or single taxonomy. If you are using multiple taxonomies then you need to define which taxonomy needs to be used in permalink. For that, You can use Yoast SEO Main Category Option.

Regards,
Sami
