### ISSUE TITLE
Does not play well with Gutenberg

### ISSUE THREAD

**Issue by adrolli** [yasglobal/permalinks-customizer#22]
I like the possibilities of permalinks-customizer but this issue keeps me from using it ...

The first and really big problem I have is that it hides all Metaboxes when in use with Gutenberg (means WP 5.3 and no Classic Editor installed). It is not very nice to hide the Permalink-Setting at the top of the Gutenberg-Editor (I searched a while until I found out, why it is missing), but I can live with that. Without Custom Fields and Yoast it is impossible for me to use the plugin.

The follow-up issue: I deactivated the plugin on my Multisite-Installation and oh wonder, it stayed active. After reactivation and deactivation on each of the subsites, it worked and the Metaboxes went back to normal.

Cheers from Vietnam,
Alf

**Comment by samiahmedsiddiqui** [comment]
@adrolli Thanks for using this plugin and reaching to us for sharing your issues and thoughts..!

> The first and really big problem I have is that it hides all Metaboxes when in use with Gutenberg
As per my knowledge and testing, Permalinks Customizer is not hiding any Metabox except itself while you are adding new post/page. On Edit, it does not hide itself as well.

I have tested this with latest Version of the plugin and WordPress 5.0.3 without Multisite-installation. Not sure if there is any issue on Multisite.

Thanks,
Sami
