### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable...

### ISSUE THREAD

**Issue by toad78** [yasglobal/permalinks-customizer#24]
Right after installation I received this error message:
Warning: count(): Parameter must be an array or an object that implements Countable in public/wp-content/plugins/custom-permalinks/admin/class-custom-permalinks-admin.php on line 300

Attempted to use the plugin as instructed but it did nothing.

**Comment by samiahmedsiddiqui** [comment]
Hi @toad78 

What's the issue you are facing while using the plugin except this warning. I will fix this warning in upcoming release.

Regards,
Sami

**Comment by toad78** [comment]
Please rephrase, as I do not understand what you are saying.

**Comment by samiahmedsiddiqui** [comment]
I mean, does the plugin is working for you or not?

I understand that you are getting the `warning` which will be fixed in the next release other than that do you have any issues with the plugin?

**Comment by samiahmedsiddiqui** [comment]
@toad78 This is **Permalinks Customizer** repo and you are using **Custom Permalinks** plugin. I have created an issue on **Custom Permalinks** repo. Here is the link:
https://github.com/yasglobal/custom-permalinks/issues/27
