### ISSUE TITLE
Hooking into url_to_postid() to make permalinks customization available to other components

### ISSUE THREAD

**Issue by TheCrowned** [yasglobal/permalinks-customizer#25]
Hi there,
we have an issue in our setup where we ask WordPress for the post ID given its permalink. We use the core url_to_postid() function. However, this doesn't work well when the permalink has been customized with the plugin, because it looks like it doesn't hook into that function. Is this expected behavior? Could the plugin into the function and have it work as expected for other modules as well, instead of just the frontend? :)

Thanks so much!
Have a nice day,
Stefano

**Comment by samiahmedsiddiqui** [comment]
Hi Stefano (@TheCrowned)

Sorry for the delay in writing back to you. I have checked this issue today and fixed it. If you are still using the `Permalinks Customizer` plugin then you may check this in `v2.6.0`.

Regards,
Sami

**Comment by TheCrowned** [comment]
Great to know! I had a customer having issues with this :)

**Comment by samiahmedsiddiqui** [comment]
@TheCrowned Ask your customer to verify this provide us their valuable feedback. This definitely helps many other WP users.
