### ISSUE TITLE
Erroneous home page redirect

### ISSUE THREAD

**Issue by dibbygit** [yasglobal/permalinks-customizer#27]
There appears to be a bug or redirect issue that is redirecting the Wordpress site home page to a product page when the woocommerce Shop page is set to be the home page.

**EXAMPLE**
1. Example URL = au.test.com
2. Home Page = woocommerce Shop page [ i.e. Wordpress Settings > Reading Settings > Your homepage displays > A static page: Hompage > Shop ]
3. PostTypes Permalinks Settings for _Products_ > https://au.test.com/%product_cat%/%postname%
4. Taxonomy Pernalinks Settings for _Product categories_ > https://au.test.com/%all_parents_slug%
5. When visiting https://au.test.com instead of showing the Shop page as the home page, the site redirects and displays the most recently created product page. e.g. https://au.test.com/category/sub-category/product-page
6. When the Site Home Page is NOT the Woocommerce Shop page, everything is OK.

It seems to be a similar problem described here: https://wpml.org/errata/redirection-issues-with-languages-in-directories-and-use-directory-for-default-language/
(But that solution doesn't work for Permalinks Customizer as it is created for a different plugin for different hooks.)

**Comment by samiahmedsiddiqui** [comment]
@dibbygit Sorry for the delayed response. I have followed your steps but doesn't found any redirect issue for myself. 

Are you using any multilingual plugin? Like WPML or Polylang. I have followed these steps with not using the multilingual plugin. Maybe, this issue is occurring due to that plugin.


Sami
