### ISSUE TITLE
Translate tag with WPML 

### ISSUE THREAD

**Issue by Spidlace** [yasglobal/permalinks-customizer#34]
Hello,

I want to translate custom tags in multiple languages. (ES/FR/IT...)
With "Translation management" from WPML, can we translate tags like this ? 

```
offer/%all_parents_slug% => oferta/%all_parents_slug% (for ES)
                         => offre/%all_parents_slug% (for FR)
                         ...
```

Thanks for your response

**Comment by samiahmedsiddiqui** [comment]
Hi @Spidlace 

No, you can not translate tags. There is no such option is available at the moment.

Regards,
Sami
