### ISSUE TITLE
%category% tag only adding first 2 level categories

### ISSUE THREAD

**Issue by avainfotech2019** [yasglobal/permalinks-customizer#37]
I am using %category%/%title% in post permalink. The permalink generated is only having first 2 level categories and not all subcategories as nested. For e.g. the post is in cat1, cat2, cat3 & cat4 the permalink generated is only cat1/cat2/title and not considering cat3 & cat4 in permalink.

**Comment by samiahmedsiddiqui** [comment]
@avainfotech2019 Change the `%category%/%title%` to `<%ctaxparents_category%>/%title%` and hopefully, it will fix your issue. 

Please provide your feedback after making changes.

**Comment by avainfotech2019** [comment]
Its working after making the changes. Thx for the reply
