### ISSUE TITLE
Conflicts occur when implementing custom bulk edit actions

### ISSUE THREAD

**Issue by mas2311** [yasglobal/permalinks-customizer#38]
I tried to add my own bulk action for a custom post type that I created.

I added the action handler using the filter _handle_bulk_actions-edit-{post_type}_, only to find that the filter is already declared by Permalinks Customizer, and can only be declared once for a given post type.

This created a conflict when trying to process my own custom action since Permalink Customizer's callback function was executing, and I was getting the following error:
`PHP Notice:  Use of undefined constant redirect_to - assumed 'redirect_to' in /Applications/MAMP/htdocs/atj/wp-content/plugins/permalinks-customizer/frontend/class-permalinks-customizer-form.php on line 1451`

I also tried to disable Permalinks Customizer for my custom post type with the _permalinks_customizer_exclude_post_type_ filter, but I kept getting the error, so I had to change the code in _add_bulk_option()_ in _class-permalinks-customizer-form.php_ to prevent it from adding the bulk action for my custom post type.

Is there a better way to solve this conflict?

Thanks for a great plugin!

**Comment by samiahmedsiddiqui** [comment]
@mas2311 Error fixed in https://github.com/yasglobal/permalinks-customizer/commit/a7d5b901c5e2b6b65a46533c1b7975100e20373c
