### ISSUE TITLE
Undefined constant

### ISSUE THREAD

**Issue by Stirius** [yasglobal/permalinks-customizer#40]
Hello,

we are seeing in our php error log the one below. Could you please check it and release an update? Thank you!

Warning: Use of undefined constant redirect_to - assumed 'redirect_to' (this will throw an Error in a future version of PHP) in /home/xxx/public_html/wp-content/plugins/permalinks-customizer/frontend/class-permalinks-customizer-form.php on line 1449

**Comment by samiahmedsiddiqui** [comment]
Hi @Stirius 

Thank you for reporting this issue, I will check that out and make it fixed in the upcoming release.
