### ISSUE TITLE
permanent links are now damaged

### ISSUE THREAD

**Issue by opritescu** [yasglobal/permalinks-customizer#41]
after i've set all 300 links, everything was working properly, since yesterday 90% of pages have 400 error found
saw more than 300 redirects pages ( i didn't do these)
please get in contact with me here / skype / whatsapp and help me on solving this asap, in 1 week i need to go live with my website but now i can't do this till this problem will be solved

**Comment by samiahmedsiddiqui** [comment]
@opritescu What have you changed on your website? It should not starts throwing 404 for no reason. There should be some change.

**Comment by opritescu** [comment]
i've added you on skype
i did't do anything that could damage this
i can send you on skype user and pass to check it

**Comment by samiahmedsiddiqui** [comment]
> i've added you on skype

I haven't got any invite. Do you know my skype ID?

**Comment by opritescu** [comment]
samiahmedsiddiqui

**Comment by opritescu** [comment]
add me on deejaymag

**Comment by samiahmedsiddiqui** [comment]
> samiahmedsiddiqui

This is not my skype ID. My skype ID is **sasiddiqui91**

**Comment by samiahmedsiddiqui** [comment]
Let's discuss this more over skype.

**Comment by opritescu** [comment]
great, i've added you
