### ISSUE TITLE
Redirect sorting does not work

### ISSUE THREAD

**Issue by chuneycutt-relias** [yasglobal/permalinks-customizer#44]
Permalinks Customizer plugin version: 2.8.0
Wordpress version: 5.4.1

When attempting sort redirects, none of the table columns respond to sorting when clicking the arrow to sort by ascending or descending. Sorting parameters are added to the URL and the page refreshes, but no changes appear in the table list of redirects.

Example:
1. I click the arrow next to Redirect From to sort by ascending
2. The page loads, and the URL updates: `www.mysite.com/wp-admin/admin.php?page=permalinks-customizer-redirects&orderby=redirect_from&order=asc`
3. The page finishes loading, but nothing changes.

I verified that this error appears when only the Permalinks Customizer plugin is active on the default Twenty Twenty theme. 

We have 4183 enabled redirects and 60 disabled redirects. 

Please reply if you need more information to debug this issue.

**Comment by samiahmedsiddiqui** [comment]
@chuneycutt-relias I found this issue and fix out as soon as possible for me.
