### ISSUE TITLE
Auto updating permalinks

### ISSUE THREAD

**Issue by samiahmedsiddiqui** [yasglobal/permalinks-customizer#7]
This plugin is really nice. though it would be perfect if it could make or have an option to make existing posts to auto update its permalinks. the case for me is that, i have custom post type (w/ existing posts) and wanted to removed CPT name slug from URL (ex:/my-custom-post-type/some-title), but its not. it only work with new created post(/some-title)…

https://wordpress.org/support/topic/not-auto-updating-permalinks/

**Comment by wilr** [comment]
Any update on a bulk update / auto update feature? Would be really handy!

**Comment by samiahmedsiddiqui** [comment]
@wilr Great to see your interest on the bulk update :)

I have not pretty much worked on this till now as this point is not looks important for users but surely, i'll go and would do it now.

Thanks again for showing your interest ;)

**Comment by samiahmedsiddiqui** [comment]
@wilr Bulk Update Feature is available now. Please get the latest version from the wordpress.org and use this feature.

Thanks,
Sami
